services:
  - type: web
    name: ai-passport
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        value: https://ai-passport-ebon.vercel.app
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NVIDIA_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
